### ISSUE TITLE
 Add an "About yourself" section to the website.

### ISSUE THREAD

**Issue by gabrielaliera** [gabrielaliera/MLH-portfolio#2]

**Comment by Mansi209aps** [comment]
Hey @gabrielaliera , I want to work on this issue. Please assign me the issue.

**Comment by gabrielaliera** [comment]
Hey @Mansi209aps , Are you part of MLH swift swans? You are supposed to work on your own fork portfolio project. This is a group project between myself and my partner. You might have the wrong project or group.

**Comment by gabrielaliera** [comment]
I will do this one and will be included in the home page
